#ifdef HAVE_CATCH2_CATCH_ALL_HPP
#include <catch2/catch_all.hpp>
#elif HAVE_CATCH2_CATCH_HPP
#include <catch2/catch.hpp>
#elif HAVE_CATCH_CATCH_HPP
#include <catch/catch.hpp>
#elif HAVE_CATCH_HPP
#include <catch.hpp>
#else
#error No catch header
#endif

#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <list>
#include <memory>
#include <mutex>
#include <string>
#include <thread>

#include "fss-transport.hpp"
#include "fss-transport-ssl.hpp"
#include "test_helpers.hpp"

/* Certs: the main certs/ tree is generated by tests/Makefile.am and
 * signed by the project CA. The certs-alt/ tree is a separate CA with
 * its own client/server pair — used here to prove that a client does
 * not trust a server signed by a foreign authority. Expired fixtures
 * live under certs/expired/. */
namespace {

constexpr const char *CA_PUBLIC_FILE = "certs/ca.public.pem";
constexpr const char *SERVER_PRIVATE_FILE = "certs/localhost.private.pem";
constexpr const char *SERVER_PUBLIC_FILE = "certs/localhost.public.pem";
constexpr const char *CLIENT_PRIVATE_FILE = "certs/client.private.pem";
constexpr const char *CLIENT_PUBLIC_FILE = "certs/client.public.pem";

constexpr const char *ALT_CA_PUBLIC_FILE = "certs-alt/ca.public.pem";
constexpr const char *ALT_CLIENT_PRIVATE_FILE = "certs-alt/client.private.pem";
constexpr const char *ALT_CLIENT_PUBLIC_FILE = "certs-alt/client.public.pem";

constexpr const char *EXPIRED_CLIENT_PRIVATE_FILE = "certs/expired/client.private.pem";
constexpr const char *EXPIRED_CLIENT_PUBLIC_FILE = "certs/expired/client.public.pem";

constexpr const char *GHOST_CLIENT_PRIVATE_FILE = "certs/ghost/client.private.pem";
constexpr const char *GHOST_CLIENT_PUBLIC_FILE = "certs/ghost/client.public.pem";

/* The accept thread writes `accepted` from its callback while the main test
 * thread reads and clears it. Funnel every access through accepted_mutex so the
 * two cannot race (TSan, todo/13.2) — the grace-window sleeps only shrank the
 * window, they did not remove it. Tests must use get_accepted()/reset_accepted()
 * rather than touching the global directly. */
std::mutex accepted_mutex;
std::shared_ptr<flight_safety_system::transport::fss_connection> accepted; // guarded by accepted_mutex

auto accept_cb(std::shared_ptr<flight_safety_system::transport::fss_connection> new_conn) -> bool
{
    const std::scoped_lock lock(accepted_mutex);
    accepted = std::move(new_conn);
    return true;
}

auto get_accepted() -> std::shared_ptr<flight_safety_system::transport::fss_connection>
{
    const std::scoped_lock lock(accepted_mutex);
    return accepted;
}

void reset_accepted()
{
    const std::scoped_lock lock(accepted_mutex);
    accepted = nullptr;
}

/* Open a raw TCP connection to the listener (IPv6 loopback) and send nothing
 * — a "silent peer" that completes the TCP handshake but never starts the TLS
 * handshake. Returns the fd (caller closes it) or -1 on failure. */
auto connect_silent_peer(uint16_t port) -> int
{
    int sock = ::socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP);
    if (sock < 0)
    {
        return -1;
    }
    struct sockaddr_in6 addr{};
    addr.sin6_family = AF_INET6;
    addr.sin6_port = htons(port);
    addr.sin6_addr = in6addr_loopback;
    if (::connect(sock, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr)) < 0)
    {
        ::close(sock);
        return -1;
    }
    return sock;
}

} // namespace

TEST_CASE("ssl: client rejects server cert signed by a different CA")
{
    reset_accepted();
    constexpr uint16_t port = 20512;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    /* Use the alt CA on the client side. The server is signed by the
     * main CA, so trust verification must fail. */
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        ALT_CA_PUBLIC_FILE, ALT_CLIENT_PRIVATE_FILE, ALT_CLIENT_PUBLIC_FILE);
    REQUIRE_FALSE(client->connectTo("localhost", port));

    /* The server should not have accepted a usable peer. Give it a
     * brief grace window — if it did produce an accepted_conn, the
     * handshake result is what matters; no identity message should
     * ever arrive. */
    std::this_thread::sleep_for(std::chrono::milliseconds(200));
    if (auto conn = get_accepted())
    {
        REQUIRE(conn->getMsg() == nullptr);
    }
    reset_accepted();
}

TEST_CASE("ssl: server rejects client presenting an expired certificate", "[ssl_expired]")
{
    reset_accepted();
    constexpr uint16_t port = 20513;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    /* Client uses an expired cert signed by the same CA. The server
     * must refuse the handshake. */
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, EXPIRED_CLIENT_PRIVATE_FILE, EXPIRED_CLIENT_PUBLIC_FILE);
    bool connected = client->connectTo("localhost", port);

    /* Either the client observes the rejection locally, or the
     * server-side handshake fails and no usable session appears. */
    std::this_thread::sleep_for(std::chrono::milliseconds(300));
    if (auto conn = get_accepted(); connected && conn != nullptr)
    {
        /* No application message should pass across an expired
         * handshake. */
        REQUIRE(conn->getMsg() == nullptr);
    }
    reset_accepted();
}

TEST_CASE("ssl: server surfaces wrong-CN-but-CA-signed cert via getClientNames", "[ssl_wrong_cn]")
{
    /* A cert validly signed by the trusted CA but whose CN is not on any
     * asset list must complete the TLS handshake — that's what the trust
     * chain proves — and the server-side accepted connection must surface
     * the cert's CN to the application layer so the identity stage can
     * reject by asset lookup.  The downstream rejection itself is unit-
     * tested in tests/server_session_test.cpp ("session: rejects identify
     * when claimed name does not match cert CN" and "session: rejects
     * identify when asset unknown to database").
     *
     * Without this integration test, getClientNames() could regress
     * silently and leave the asset-name check working only against the
     * synthetic FakeConnection used in unit tests. */
    reset_accepted();
    constexpr uint16_t port = 20514;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, GHOST_CLIENT_PRIVATE_FILE, GHOST_CLIENT_PUBLIC_FILE);
    REQUIRE(client->connectTo("localhost", port));

    REQUIRE(fss_test::wait_for([]() { return get_accepted() != nullptr; }));

    auto conn = get_accepted();
    REQUIRE(conn != nullptr);
    std::list<std::string> names = conn->getClientNames();
    REQUIRE_FALSE(names.empty());
    bool found = std::any_of(names.begin(), names.end(), [](const std::string &n) { return n == "ghost-asset"; });
    REQUIRE(found);

    reset_accepted();
}

TEST_CASE("ssl: server rejects a client cert signed by an untrusted CA", "[ssl_foreign_client_cert]")
{
    /* Authentication bypass regression: GNUTLS_CERT_REQUIRE forces the
     * client to present a cert but does not by itself verify it chains to
     * the trusted CA. The server must reject a cert signed by a foreign CA
     * during the handshake, so it never reaches the CN-based identity check
     * — otherwise a self-signed cert carrying a known asset CN would
     * authenticate. The client trusts the main CA (so it accepts the
     * server); it presents an alt-CA client cert the server does not trust.
     * A correctly verifying server must surface NO client name. */
    reset_accepted();
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, ALT_CLIENT_PRIVATE_FILE, ALT_CLIENT_PUBLIC_FILE);
    /* The client's own verification of the (trusted) server may briefly
     * succeed before the server aborts; we don't assert on connectTo's
     * result, only that the server never accepts the foreign identity. */
    client->connectTo("localhost", port);

    /* The server-side handshake must fail verification, so create() returns
     * nullptr and the accept callback is never invoked — the untrusted cert
     * yields no connection at all (a strictly stronger guarantee than the
     * pre-1.1.0 behaviour, which surfaced a nameless connection). If the
     * server regressed and accepted the foreign cert, the callback would fire
     * and `accepted` would become non-null within the grace window. */
    REQUIRE_FALSE(fss_test::wait_for([]() { return get_accepted() != nullptr; }, std::chrono::milliseconds(500)));
    listen = nullptr;
    reset_accepted();
}

TEST_CASE("ssl: misconfigured cert paths fail without throwing")
{
    /* Regression: set_x509_trust_file / set_x509_key_file throw
     * gnutls::exception on a missing or unreadable file, and those calls
     * were outside any try block — a misconfigured client crashed instead
     * of logging and returning failure.  The library contract is that no
     * gnutls exception escapes: connectTo() returns false and create()
     * returns nullptr.  A live listener is required so the TCP connect
     * succeeds and the failure happens in TLS setup, not before it. */
    reset_accepted();
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    SECTION("nonexistent CA file")
    {
        auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
            "certs/no-such-ca.pem", CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
        bool connected = true;
        REQUIRE_NOTHROW(connected = client->connectTo("localhost", port));
        REQUIRE_FALSE(connected);
    }

    SECTION("nonexistent client key")
    {
        auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
            CA_PUBLIC_FILE, "certs/no-such-key.pem", CLIENT_PUBLIC_FILE);
        bool connected = true;
        REQUIRE_NOTHROW(connected = client->connectTo("localhost", port));
        REQUIRE_FALSE(connected);
    }

    SECTION("create() with nonexistent key returns nullptr")
    {
        std::shared_ptr<flight_safety_system::transport_ssl::fss_connection_client> client;
        REQUIRE_NOTHROW(client = flight_safety_system::transport_ssl::fss_connection_client::create(
                            CA_PUBLIC_FILE, "certs/no-such-key.pem", CLIENT_PUBLIC_FILE, "localhost", port));
        REQUIRE(client == nullptr);
    }

    /* Tear the listener down (joining the accept thread) before clearing, so a
     * late callback cannot resurrect `accepted` after the reset. The mutex
     * already makes the accesses themselves race-free; this just keeps the
     * end-state deterministic. */
    listen = nullptr;
    reset_accepted();
}

TEST_CASE("ssl: getSessionDesc on unconnected client returns empty string")
{
    auto conn = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
    REQUIRE(conn->getSessionDesc().empty());
}

TEST_CASE("ssl: sendMsg on unconnected client returns false")
{
    // usable == false before connectTo() — sendMsg must refuse immediately.
    // Cast to base to call the public sendMsg(fss_message) overload (the SSL
    // subclass's protected sendMsg(buf_len) would otherwise hide it).
    std::shared_ptr<flight_safety_system::transport::fss_connection> conn =
        std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
            CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
    auto msg = std::make_shared<flight_safety_system::transport::fss_message_identity>("test");
    REQUIRE_FALSE(conn->sendMsg(msg));
}

TEST_CASE("ssl: isPeerCertRevoked with non-existent CRL file returns false")
{
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    fss_test::connection_handoff handoff;

    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, handoff.callback(), CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);

    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
    REQUIRE(client->connectTo("localhost", port));

    auto server_conn = handoff.wait();
    REQUIRE(server_conn != nullptr);

    REQUIRE_FALSE(server_conn->isPeerCertRevoked("/nonexistent/path/crl.pem"));

    server_conn = nullptr;
    handoff.reset();
}

TEST_CASE("ssl: a silent peer does not block other clients' handshakes", "[ssl_handshake_dos]")
{
    /* Regression for the accept-thread DoS: a peer that completes the TCP
     * connection but never sends a ClientHello must not block new
     * connections. Before the off-accept-thread refactor the listener ran the
     * TLS handshake inline, so this test would have wedged the accept thread
     * and hung the suite. A short handshake timeout keeps teardown quick. */
    reset_accepted();
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    /* Use the default (generous) handshake timeout. The same timeout applies to
     * the legitimate client's server-side handshake, and under a slow build
     * (e.g. valgrind) a real TLS handshake can take seconds — a short timeout
     * would spuriously time out the good client. The silent peer is drained
     * promptly at teardown by closing it (the EOF aborts its handshake), so the
     * generous timeout does not slow the test down. */
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);
    constexpr auto generous = std::chrono::milliseconds(15000); // tolerate valgrind slowdown

    int silent = connect_silent_peer(port);
    REQUIRE(silent >= 0);
    /* The silent peer should occupy a setup worker (mid-handshake). */
    REQUIRE(fss_test::wait_for([&]() { return listen->getActiveSetupCount() >= 1; }, generous));

    /* A well-behaved client must still complete its handshake while the silent
     * peer is stuck — proving the accept thread is not blocked. */
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
    REQUIRE(client->connectTo("localhost", port));
    REQUIRE(fss_test::wait_for([]() { return get_accepted() != nullptr; }, generous));

    ::close(silent);
    listen = nullptr; // close() above aborts the silent worker's handshake, draining it
    reset_accepted();
}

TEST_CASE("ssl: concurrent handshakes are bounded and excess connections shed", "[ssl_handshake_bound]")
{
    /* The setup-worker pool is bounded so the off-thread handshake path cannot
     * itself be used to exhaust threads/memory: once the bound is reached,
     * further accepted connections are closed immediately rather than queued. */
    reset_accepted();
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    constexpr size_t max_handshakes = 2;
    /* Generous handshake timeout so the silent peers reliably hold their slots
     * for the duration (the bound is what's under test, not the timeout); they
     * are drained by close() at teardown. A short timeout would let the slots
     * free mid-test under a slow build and the excess connection would not be
     * shed. */
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE, std::string{},
        flight_safety_system::transport_ssl::default_handshake_timeout_ms, max_handshakes);
    REQUIRE(listen != nullptr);
    constexpr auto generous = std::chrono::milliseconds(15000); // tolerate valgrind slowdown

    /* Fill every setup slot with silent peers. */
    std::array<int, max_handshakes> silent{};
    for (auto &fd : silent)
    {
        fd = connect_silent_peer(port);
        REQUIRE(fd >= 0);
    }
    REQUIRE(fss_test::wait_for([&]() { return listen->getActiveSetupCount() >= max_handshakes; }, generous));

    /* An additional connection is accepted at the TCP layer but must be shed:
     * the rejected counter advances and the peer observes an immediate EOF. */
    int extra = connect_silent_peer(port);
    REQUIRE(extra >= 0);
    REQUIRE(fss_test::wait_for([&]() { return listen->getRejectedSetupCount() >= 1; }, generous));
    char buf = 0;
    REQUIRE(::recv(extra, &buf, 1, 0) == 0); // orderly close from the server side

    ::close(extra);
    for (auto fd : silent)
    {
        ::close(fd);
    }
    listen = nullptr;
    reset_accepted();
}

TEST_CASE("ssl: client handshake times out against a silent server", "[ssl_handshake_dos]")
{
    /* Client side of the same DoS: a server that completes the TCP connection
     * but never performs the TLS handshake must not hang connectTo()
     * indefinitely. fss_connection_client bounds its handshake via
     * gnutls_handshake_set_timeout; a short injected timeout keeps this fast. */
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);

    /* A raw TCP server that accepts one connection and then stays silent. */
    int listen_fd = ::socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP);
    REQUIRE(listen_fd >= 0);
    int reuse = 1;
    (void)::setsockopt(listen_fd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
    struct sockaddr_in6 addr{};
    addr.sin6_family = AF_INET6;
    addr.sin6_port = htons(port);
    addr.sin6_addr = in6addr_any;
    REQUIRE(::bind(listen_fd, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr)) == 0);
    REQUIRE(::listen(listen_fd, 1) == 0);

    std::atomic<bool> stop{false};
    std::thread silent_server([&]() {
        int peer = ::accept(listen_fd, nullptr, nullptr); // unblocked by closing listen_fd below
        while (!stop.load())
        {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
        }
        if (peer >= 0)
        {
            ::close(peer);
        }
    });

    constexpr unsigned int client_handshake_ms = 1000;
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE, client_handshake_ms);

    auto start = std::chrono::steady_clock::now();
    bool connected = client->connectTo("localhost", port);
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - start);

    REQUIRE_FALSE(connected);
    /* It must wait for (roughly) the injected timeout, not fail instantly... */
    REQUIRE(elapsed >= std::chrono::milliseconds(client_handshake_ms / 2));
    /* ...and give up clearly before the default handshake timeout — proving the
     * injected timeout took effect — derived from the real constant (not a
     * literal) so it tracks the default, with 10% slack for valgrind overhead. */
    constexpr auto default_handshake_timeout =
        std::chrono::milliseconds(flight_safety_system::transport_ssl::default_handshake_timeout_ms);
    REQUIRE(elapsed < default_handshake_timeout * 9 / 10);

    stop.store(true);
    ::close(listen_fd); // also unblocks accept() if the client never connected
    silent_server.join();
}
