#ifdef HAVE_CATCH2_CATCH_ALL_HPP
#include <catch2/catch_all.hpp>
#elif HAVE_CATCH2_CATCH_HPP
#include <catch2/catch.hpp>
#elif HAVE_CATCH_CATCH_HPP
#include <catch/catch.hpp>
#elif HAVE_CATCH_HPP
#include <catch.hpp>
#else
#error No catch header
#endif

#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#include <atomic>
#include <chrono>
#include <memory>
#include <thread>

#include "fss-transport.hpp"
#include "fss-transport-ssl.hpp"
#include "test_helpers.hpp"

/* Certs: the main certs/ tree is generated by tests/Makefile.am and
 * signed by the project CA. The certs-alt/ tree is a separate CA with
 * its own client/server pair — used here to prove that a client does
 * not trust a server signed by a foreign authority. Expired fixtures
 * live under certs/expired/. */
namespace {

constexpr const char *CA_PUBLIC_FILE     = "certs/ca.public.pem";
constexpr const char *SERVER_PRIVATE_FILE = "certs/localhost.private.pem";
constexpr const char *SERVER_PUBLIC_FILE  = "certs/localhost.public.pem";
constexpr const char *CLIENT_PRIVATE_FILE = "certs/client.private.pem";
constexpr const char *CLIENT_PUBLIC_FILE  = "certs/client.public.pem";

constexpr const char *ALT_CA_PUBLIC_FILE     = "certs-alt/ca.public.pem";
constexpr const char *ALT_CLIENT_PRIVATE_FILE = "certs-alt/client.private.pem";
constexpr const char *ALT_CLIENT_PUBLIC_FILE  = "certs-alt/client.public.pem";

constexpr const char *EXPIRED_CLIENT_PRIVATE_FILE = "certs/expired/client.private.pem";
constexpr const char *EXPIRED_CLIENT_PUBLIC_FILE  = "certs/expired/client.public.pem";

std::shared_ptr<flight_safety_system::transport::fss_connection> accepted;

auto accept_cb(std::shared_ptr<flight_safety_system::transport::fss_connection> new_conn) -> bool
{
    accepted = std::move(new_conn);
    return true;
}

} // namespace

TEST_CASE("ssl: client rejects server cert signed by a different CA")
{
    accepted = nullptr;
    constexpr uint16_t port = 20512;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    /* Use the alt CA on the client side. The server is signed by the
     * main CA, so trust verification must fail. */
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        ALT_CA_PUBLIC_FILE, ALT_CLIENT_PRIVATE_FILE, ALT_CLIENT_PUBLIC_FILE);
    REQUIRE_FALSE(client->connectTo("localhost", port));

    /* The server should not have accepted a usable peer. Give it a
     * brief grace window — if it did produce an accepted_conn, the
     * handshake result is what matters; no identity message should
     * ever arrive. */
    std::this_thread::sleep_for(std::chrono::milliseconds(200));
    if (accepted != nullptr)
    {
        REQUIRE(accepted->getMsg() == nullptr);
    }
    accepted = nullptr;
}

TEST_CASE("ssl: server rejects client presenting an expired certificate",
          "[ssl_expired]")
{
    accepted = nullptr;
    constexpr uint16_t port = 20513;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    /* Client uses an expired cert signed by the same CA. The server
     * must refuse the handshake. */
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, EXPIRED_CLIENT_PRIVATE_FILE, EXPIRED_CLIENT_PUBLIC_FILE);
    bool connected = client->connectTo("localhost", port);

    /* Either the client observes the rejection locally, or the
     * server-side handshake fails and no usable session appears. */
    std::this_thread::sleep_for(std::chrono::milliseconds(300));
    if (connected && accepted != nullptr)
    {
        /* No application message should pass across an expired
         * handshake. */
        REQUIRE(accepted->getMsg() == nullptr);
    }
    accepted = nullptr;
}

/* Deliberately omitted: a "silent raw-TCP peer blocks the accept thread"
 * regression test. The current server architecture performs the TLS
 * handshake inline on the accept thread, which means a single silent
 * peer wedges the listener indefinitely. Exercising that would deadlock
 * the test binary. Capturing this as a regression requires the
 * server-side refactor tracked in Phase 4 (move handshake off the
 * accept thread). */
