#ifdef HAVE_CATCH2_CATCH_ALL_HPP
#include <catch2/catch_all.hpp>
#elif HAVE_CATCH2_CATCH_HPP
#include <catch2/catch.hpp>
#elif HAVE_CATCH_CATCH_HPP
#include <catch/catch.hpp>
#elif HAVE_CATCH_HPP
#include <catch.hpp>
#else
#error No catch header
#endif

#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <list>
#include <memory>
#include <string>
#include <thread>

#include "fss-transport.hpp"
#include "fss-transport-ssl.hpp"
#include "test_helpers.hpp"

/* Certs: the main certs/ tree is generated by tests/Makefile.am and
 * signed by the project CA. The certs-alt/ tree is a separate CA with
 * its own client/server pair — used here to prove that a client does
 * not trust a server signed by a foreign authority. Expired fixtures
 * live under certs/expired/. */
namespace {

constexpr const char *CA_PUBLIC_FILE = "certs/ca.public.pem";
constexpr const char *SERVER_PRIVATE_FILE = "certs/localhost.private.pem";
constexpr const char *SERVER_PUBLIC_FILE = "certs/localhost.public.pem";
constexpr const char *CLIENT_PRIVATE_FILE = "certs/client.private.pem";
constexpr const char *CLIENT_PUBLIC_FILE = "certs/client.public.pem";

constexpr const char *ALT_CA_PUBLIC_FILE = "certs-alt/ca.public.pem";
constexpr const char *ALT_CLIENT_PRIVATE_FILE = "certs-alt/client.private.pem";
constexpr const char *ALT_CLIENT_PUBLIC_FILE = "certs-alt/client.public.pem";

constexpr const char *EXPIRED_CLIENT_PRIVATE_FILE = "certs/expired/client.private.pem";
constexpr const char *EXPIRED_CLIENT_PUBLIC_FILE = "certs/expired/client.public.pem";

constexpr const char *GHOST_CLIENT_PRIVATE_FILE = "certs/ghost/client.private.pem";
constexpr const char *GHOST_CLIENT_PUBLIC_FILE = "certs/ghost/client.public.pem";

std::shared_ptr<flight_safety_system::transport::fss_connection> accepted;

auto accept_cb(std::shared_ptr<flight_safety_system::transport::fss_connection> new_conn) -> bool
{
    accepted = std::move(new_conn);
    return true;
}

} // namespace

TEST_CASE("ssl: client rejects server cert signed by a different CA")
{
    accepted = nullptr;
    constexpr uint16_t port = 20512;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    /* Use the alt CA on the client side. The server is signed by the
     * main CA, so trust verification must fail. */
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        ALT_CA_PUBLIC_FILE, ALT_CLIENT_PRIVATE_FILE, ALT_CLIENT_PUBLIC_FILE);
    REQUIRE_FALSE(client->connectTo("localhost", port));

    /* The server should not have accepted a usable peer. Give it a
     * brief grace window — if it did produce an accepted_conn, the
     * handshake result is what matters; no identity message should
     * ever arrive. */
    std::this_thread::sleep_for(std::chrono::milliseconds(200));
    if (accepted != nullptr)
    {
        REQUIRE(accepted->getMsg() == nullptr);
    }
    accepted = nullptr;
}

TEST_CASE("ssl: server rejects client presenting an expired certificate", "[ssl_expired]")
{
    accepted = nullptr;
    constexpr uint16_t port = 20513;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    /* Client uses an expired cert signed by the same CA. The server
     * must refuse the handshake. */
    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, EXPIRED_CLIENT_PRIVATE_FILE, EXPIRED_CLIENT_PUBLIC_FILE);
    bool connected = client->connectTo("localhost", port);

    /* Either the client observes the rejection locally, or the
     * server-side handshake fails and no usable session appears. */
    std::this_thread::sleep_for(std::chrono::milliseconds(300));
    if (connected && accepted != nullptr)
    {
        /* No application message should pass across an expired
         * handshake. */
        REQUIRE(accepted->getMsg() == nullptr);
    }
    accepted = nullptr;
}

TEST_CASE("ssl: server surfaces wrong-CN-but-CA-signed cert via getClientNames", "[ssl_wrong_cn]")
{
    /* A cert validly signed by the trusted CA but whose CN is not on any
     * asset list must complete the TLS handshake — that's what the trust
     * chain proves — and the server-side accepted connection must surface
     * the cert's CN to the application layer so the identity stage can
     * reject by asset lookup.  The downstream rejection itself is unit-
     * tested in tests/server_session_test.cpp ("session: rejects identify
     * when claimed name does not match cert CN" and "session: rejects
     * identify when asset unknown to database").
     *
     * Without this integration test, getClientNames() could regress
     * silently and leave the asset-name check working only against the
     * synthetic FakeConnection used in unit tests. */
    accepted = nullptr;
    constexpr uint16_t port = 20514;
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, GHOST_CLIENT_PRIVATE_FILE, GHOST_CLIENT_PUBLIC_FILE);
    REQUIRE(client->connectTo("localhost", port));

    REQUIRE(fss_test::wait_for([]() { return accepted != nullptr; }));

    std::list<std::string> names = accepted->getClientNames();
    REQUIRE_FALSE(names.empty());
    bool found = std::any_of(names.begin(), names.end(), [](const std::string &n) { return n == "ghost-asset"; });
    REQUIRE(found);

    accepted = nullptr;
}

TEST_CASE("ssl: server rejects a client cert signed by an untrusted CA", "[ssl_foreign_client_cert]")
{
    /* Authentication bypass regression: GNUTLS_CERT_REQUIRE forces the
     * client to present a cert but does not by itself verify it chains to
     * the trusted CA. The server must reject a cert signed by a foreign CA
     * during the handshake, so it never reaches the CN-based identity check
     * — otherwise a self-signed cert carrying a known asset CN would
     * authenticate. The client trusts the main CA (so it accepts the
     * server); it presents an alt-CA client cert the server does not trust.
     * A correctly verifying server must surface NO client name. */
    accepted = nullptr;
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, ALT_CLIENT_PRIVATE_FILE, ALT_CLIENT_PUBLIC_FILE);
    /* The client's own verification of the (trusted) server may briefly
     * succeed before the server aborts; we don't assert on connectTo's
     * result, only that the server never accepts the foreign identity. */
    client->connectTo("localhost", port);

    /* The SSL listener runs the handshake synchronously before invoking the
     * accept callback, so once accepted is set the server has finished (and
     * rejected) verification; a correctly verifying server surfaces no CN. */
    REQUIRE(fss_test::wait_for([]() { return accepted != nullptr; }));
    REQUIRE(accepted->getClientNames().empty());
    accepted = nullptr;
}

TEST_CASE("ssl: misconfigured cert paths fail without throwing")
{
    /* Regression: set_x509_trust_file / set_x509_key_file throw
     * gnutls::exception on a missing or unreadable file, and those calls
     * were outside any try block — a misconfigured client crashed instead
     * of logging and returning failure.  The library contract is that no
     * gnutls exception escapes: connectTo() returns false and create()
     * returns nullptr.  A live listener is required so the TCP connect
     * succeeds and the failure happens in TLS setup, not before it. */
    accepted = nullptr;
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port, accept_cb, CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);
    REQUIRE(listen != nullptr);

    SECTION("nonexistent CA file")
    {
        auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
            "certs/no-such-ca.pem", CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
        bool connected = true;
        REQUIRE_NOTHROW(connected = client->connectTo("localhost", port));
        REQUIRE_FALSE(connected);
    }

    SECTION("nonexistent client key")
    {
        auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
            CA_PUBLIC_FILE, "certs/no-such-key.pem", CLIENT_PUBLIC_FILE);
        bool connected = true;
        REQUIRE_NOTHROW(connected = client->connectTo("localhost", port));
        REQUIRE_FALSE(connected);
    }

    SECTION("create() with nonexistent key returns nullptr")
    {
        std::shared_ptr<flight_safety_system::transport_ssl::fss_connection_client> client;
        REQUIRE_NOTHROW(client = flight_safety_system::transport_ssl::fss_connection_client::create(
                            CA_PUBLIC_FILE, "certs/no-such-key.pem", CLIENT_PUBLIC_FILE, "localhost", port));
        REQUIRE(client == nullptr);
    }

    /* Join the accept thread (which assigns the `accepted` global from its
     * callback) before clearing the global, so the two writes can't race. */
    listen = nullptr;
    accepted = nullptr;
}

TEST_CASE("ssl: getSessionDesc on unconnected client returns empty string")
{
    auto conn = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
    REQUIRE(conn->getSessionDesc().empty());
}

TEST_CASE("ssl: sendMsg on unconnected client returns false")
{
    // usable == false before connectTo() — sendMsg must refuse immediately.
    // Cast to base to call the public sendMsg(fss_message) overload (the SSL
    // subclass's protected sendMsg(buf_len) would otherwise hide it).
    std::shared_ptr<flight_safety_system::transport::fss_connection> conn =
        std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
            CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
    auto msg = std::make_shared<flight_safety_system::transport::fss_message_identity>("test");
    REQUIRE_FALSE(conn->sendMsg(msg));
}

TEST_CASE("ssl: isPeerCertRevoked with non-existent CRL file returns false")
{
    const uint16_t port = fss_test::pick_port();
    REQUIRE(port != 0);
    std::shared_ptr<flight_safety_system::transport::fss_connection> server_conn;

    auto listen = std::make_shared<flight_safety_system::transport_ssl::fss_listen>(
        port,
        [&server_conn](std::shared_ptr<flight_safety_system::transport::fss_connection> c) -> bool {
            server_conn = std::move(c);
            return true;
        },
        CA_PUBLIC_FILE, SERVER_PRIVATE_FILE, SERVER_PUBLIC_FILE);

    auto client = std::make_shared<flight_safety_system::transport_ssl::fss_connection_client>(
        CA_PUBLIC_FILE, CLIENT_PRIVATE_FILE, CLIENT_PUBLIC_FILE);
    REQUIRE(client->connectTo("localhost", port));

    REQUIRE(fss_test::wait_for([&] { return server_conn != nullptr; }));

    REQUIRE_FALSE(server_conn->isPeerCertRevoked("/nonexistent/path/crl.pem"));

    server_conn = nullptr;
}

/* Deliberately omitted: a "silent raw-TCP peer blocks the accept thread"
 * regression test. The current server architecture performs the TLS
 * handshake inline on the accept thread, which means a single silent
 * peer wedges the listener indefinitely. Exercising that would deadlock
 * the test binary. Capturing this as a regression requires the
 * server-side refactor tracked in Phase 4 (move handshake off the
 * accept thread). */
