name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Deps
      run: sudo apt install -y libjsoncpp-dev libecpg-dev catch libgnutlsxx28 libgnutls28-dev gnutls-bin
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-tests --enable-server --enable-coverage --enable-fake-client
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
